name: sittara_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  google_fonts: ^6.3.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.3
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
